# Site settings
title: Fought for Thoughts
email: iitkauv@gmail.com
copyright_name: Fought for Thoughts
github_username: michaelp59024

collections:
  vehicles :
  teams:
  subteam :
  competition :
  research :
  people:

# used to estimate reading time
wpm: 150

port: 4444
permalink: /blog/:title

# jekyll-paginate
paginate: 5
paginate_path: blog/page:num

# gem dependencies
gems: [jekyll-paginate, jekyll-feed, jekyll-gist]
